grasping_geometric_primitives:
#####     PRIMITIVES    #####
 - name: gripper_r_frame
   type: frame 
   frame_id: gripper_r_base
   visible: true
   color: [0.0, 0.5, 0.0, 1.0]
   parameters: [0.0, 0.0, 0.15, 0.0, 0.0, 0.0]
 - name: gripper_l_frame
   type: frame 
   frame_id: gripper_l_base
   visible: true
   color: [0.0, 0.5, 0.0, 1.0]
   parameters: [0.0, 0.0, 0.15, 0.0, 0.0, 0.0]
 - name: pre_grasp_r_frame
   type: frame 
   frame_id: yumi_base_link
   visible: true
   color: [0.0, 0.5, 0.0, 1.0]
   parameters: [0.35, -0.15, 0.2, -1.57, 0.0, 1.57]
 - name: pre_grasp_l_frame
   type: frame 
   frame_id: yumi_base_link
   visible: true
   color: [0.0, 0.5, 0.0, 1.0]
   parameters: [0.35, 0.15, 0.2, 1.57, 0.0, 1.57]

#####     TASKS    #####
pre_grasp_tasks:
 - name: pre_grasp_r_track
   priority: 2
   visible: true
   active: true
   monitored: true
   def_params: ['TDefTracking', 'frame', 'frame', 'gripper_r_frame = pre_grasp_r_frame', '0.1']
   dyn_params: ['TDynPD', '3.0', '4.0']
#   def_params: ['TDefTracking', 'frame', 'frame', 'gripper_r_frame = pre_grasp_r_frame', '0.1', '0.5']
#   dyn_params: ['TDynPD', '10.0', '10.0', '10.0', '2.0', '2.0', '2.0', '7.0', '7.0', '7.0', '3.0', '3.0', '3.0']
 - name: pre_grasp_l_track
   priority: 2
   visible: true
   active: true
   monitored: true
   def_params: ['TDefTracking', 'frame', 'frame', 'gripper_l_frame = pre_grasp_l_frame', '0.1']
   dyn_params: ['TDynPD', '3.0', '4.0']
#   def_params: ['TDefTracking', 'frame', 'frame', 'gripper_l_frame = pre_grasp_l_frame', '0.1', '0.5']
#   dyn_params: ['TDynPD', '10.0', '10.0', '10.0', '2.0', '2.0', '2.0', '7.0', '7.0', '7.0', '3.0', '3.0', '3.0']
# - name: neutral pose
#   priority: 3
#   visible: true
#   active: true
#   monitored: false
#   def_params: ['TDefFullPose']
#   dyn_params: ['TDynPD', '2.0', '3.0']
   
grasp_tasks:
 - name: grasp_r_track
   priority: 2
   visible: true
   active: true
   monitored: true
   def_params: ['TDefTracking', 'frame', 'frame', 'gripper_r_frame = grasp_r_frame', '0.1', '0.5']
   dyn_params: ['TDynPD', '10.0', '10.0', '10.0', '2.0', '2.0', '2.0', '7.0', '7.0', '7.0', '3.0', '3.0', '3.0']
 - name: grasp_l_track
   priority: 2
   visible: true
   active: true
   monitored: true
   def_params: ['TDefTracking', 'frame', 'frame', 'gripper_l_frame = grasp_l_frame', '0.1', '0.5']
   dyn_params: ['TDynPD', '10.0', '10.0', '10.0', '2.0', '2.0', '2.0', '7.0', '7.0', '7.0', '3.0', '3.0', '3.0']
# - name: neutral pose
#   priority: 3
#   visible: true
#   active: true
#   monitored: false
#   def_params: ['TDefFullPose']
#   dyn_params: ['TDynPD', '2.0', '3.0']
   
#drop_assisted_tasks:
# - name: drop_left_track
#   priority: 2
#   visible: true
#   active: true
#   def_params: ['TDefTracking', 'point', 'frame', 'teleop_gripper_point = teleop_left_frame', '0.04']
#   dyn_params: ['TDynPD', '3.0', '4.0']
# - name: auto_align_bin
#   priority: 2
#   visible: true
#   active: true
#   def_params: ['TDefGeomAlign', 'frame', 'cylinder', 'teleop_gripper_frame = bin_cylinder']
#   dyn_params: ['TDynPD', '1.0', '2.0']
# - name: teleop_left_track
#   priority: 2
#   visible: true
#   active: true
#   def_params: ['TDefTracking', 'frame', 'frame', 'teleop_gripper_frame = teleop_left_frame', '0.04']
#   dyn_params: ['TDynPD', '1.0', '3.0']
   
#point_assisted_tasks:
# - name: teleop_left_track
#   priority: 2
#   active: true
#   def_params: ['TDefTracking', 'point', 'frame', 'teleop_gripper_point = teleop_left_frame', '0.04']
#   dyn_params: ['TDynPD', '3.0', '4.0']
# - name: auto_left_align
#   priority: 2
#   visible: true
#   active: true
#   def_params: ['TDefGeomAlign', 'frame', 'frame', 'target_frame = teleop_gripper_frame']
#   dyn_params: ['TDynPD', '1.0', '2.0']
   
joint_config_tasks:
 - name: joint_config_start
   priority: 2
   visible: true
   active: true
   monitored: true
   def_params: ['TDefFullPose', '-0.42', '-1.48', '1.21', '0.75', '-0.8', '0.45', '0.21', '0.42', '-1.48', '-1.21', '0.75', '0.8', '0.45', '1.21']
   dyn_params: ['TDynPD', '2.0', '3.0']
